# Generated by Django 4.2.7 on 2023-11-21 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Produto Favorito',
                'verbose_name_plural': 'Favoritos Por Usuário',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=24)),
                ('descricao_curta', models.TextField(max_length=255, verbose_name='Descrição curta')),
                ('descricao_longa', models.TextField(verbose_name='Descrição longa')),
                ('imagem', models.URLField(blank=True, null=True, verbose_name='Imagem 1')),
                ('imagem2', models.URLField(blank=True, null=True, verbose_name='Imagem 2')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('preco_marketing', models.FloatField(verbose_name='Preço')),
                ('preco_marketing_promocional', models.FloatField(default=0, verbose_name='Preço Promo. ')),
                ('tipo', models.CharField(choices=[('N', 'Nenhum'), ('D', 'Destaque'), ('L', 'Lançamento'), ('V', 'Mais Vendido')], default='L', max_length=1)),
                ('categoria_produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categoria.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Variacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=3, verbose_name='Nome (Máx de 3 caracteres)')),
                ('preco', models.FloatField(verbose_name='Preço')),
                ('preco_promocional', models.FloatField(default=0, verbose_name='Preço promocional')),
                ('estoque', models.PositiveBigIntegerField(default=1)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
            ],
            options={
                'verbose_name': 'Variação',
                'verbose_name_plural': 'Variações (obrigatório)',
            },
        ),
        migrations.CreateModel(
            name='ItemFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('produto', models.CharField(max_length=255)),
                ('produto_id', models.PositiveIntegerField()),
                ('preco', models.FloatField(verbose_name='Preço')),
                ('preco_promocional', models.FloatField(default=0, verbose_name='Preço Promocional')),
                ('slug', models.CharField(max_length=255)),
                ('imagem', models.CharField(max_length=2000)),
                ('favorito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.favorito')),
            ],
            options={
                'verbose_name': 'Item favorito',
                'verbose_name_plural': 'Itens favoritados',
            },
        ),
    ]
